
[Misc]
	#Stack Size
	#Range: 1 ~ 64
	stacksize = 15
	#How many items drop when a loot bag is used
	#Range: 1 ~ 1000
	dropamount = 10
	#Enable debug mode
	debugmode = false

["Mob Drops"]
	#Mob drops list (Syntax " mob name ")
	mobdropslist = ["blaze", "cavespider", "creeper", "drowned", "elder_guardian", "enderman", "endermite", "evoker"]
	#Loot Bag drop chance from mobs (the higher the number the more common they are)
	#Range: 1 ~ 100
	dropchance = 10

["Black And White Lists"]
	#Use the whitelist
	enablewhitelist = false
	#BlackList (Syntax "minecraft or modid : item or block name"; example "minecraft:air" or "lootbagmod:lootbag")
	blacklist = ["minecraft:air", "minecraft:command_block", "minecraft:structure_block", "minecraft:knowledge_book", "minecraft:chain_command_block", "minecraft:repeating_command_block", "minecraft:barrier", "minecraft:enchanted_book", "minecraft:written_book", "minecraft:potion", "minecraft:splash_potion", "minecraft:lingering_potion", "minecraft:spawn_egg", "minecraft:structure_void", "minecraft:mob_spawner", "minecraft:bedrock"]
	#Mod blacklist (Syntax " modid ")
	modblacklist = ["tconstruct"]
	#WhiteList Syntax "minecraft or modid : item or block name"; example minecraft:air or lootbagmod:lootbag)
	whitelist = ["minecraft:stone"]
	#TagList (Syntax "minecraft, forge or modid : tag name"; example "minecraft:planks" or "forge:planks")
	taglist = []

