
#General settings
[general]
	#Weight of a golden case dropping
	#Range: 0 ~ 100
	gold_chance = 20
	#Range: 0 ~ 100
	gold_rolls = 5
	#Weight for a throwable weapon to drop from case
	#Range: 0 ~ 100
	throwing_weight = 6
	#Weight of a titan case dropping
	#Range: 0 ~ 100
	titan_chance = 70
	#Weight for a shovel to drop from case
	#Range: 0 ~ 100
	spade_weight = 8
	#Minimum attack speed a shovel can have.
	#Range: -4.0 ~ 4.0
	spade_a_speed = -2.8
	#Weight for a pick to drop from case
	#Range: 0 ~ 100
	pick_weight = 15
	#Minimum damage a shovel can do.
	#Range: 0 ~ 100
	spade_damage = 3
	#Odds of an item getting a buff rather than a trait on a stats roll (editor upgrade, tool init, etc.)
	#Range: 0 ~ 100
	trait_ratio = 10
	#Minimum armor points armor can have.
	#Range: 0.0 ~ 100.0
	toughness = 1.0
	#Initital Rolls for traits/stats
	#Range: 0 ~ 100
	basic_rolls = 2
	#Minimum damage an axe can do.
	#Range: 0 ~ 100
	axe_damage = 9
	#Weight for a sword to drop from case
	#Range: 0 ~ 100
	sword_weight = 20
	#Bosses drop chance
	#Range: 0 ~ 100
	boss_drops = 100
	#Minimum speed a sword can have.
	#Range: -4.0 ~ 4.0
	sword_speed = -2.4
	#Initital Max XP for tools.
	#Range: 0 ~ 10000
	init_xp = 256
	#Weight for any given piece of armor to drop from case
	#Range: 0 ~ 100
	armor_weight = 1
	#Chance of a case dropping
	#Range: 0 ~ 100
	total_chance = 10
	#Minimum damage a pickaxe can do.
	#Range: 0 ~ 100
	pick_damage = 3
	#Minimum damage a sword can do.
	#Range: 0 ~ 100
	sword_damage = 7
	#Minimum attack speed a pickaxe can have.
	#Range: -4.0 ~ 4.0
	pick_a_speed = -2.8
	#Minimum armor points armor can have.
	#Range: 0 ~ 100
	armor = 4
	#Weight of a basic case dropping
	#Range: 0 ~ 100
	basic_chance = 70
	#Weight for and axe to drop from case
	#Range: 0 ~ 100
	axe_weight = 10
	#Minimum damage a throwable can do.
	#Range: 0 ~ 100
	throw_damage = 5
	#Range: 0 ~ 100
	titan_rolls = 9
	#Monsters drop chance
	#Range: 0 ~ 100
	monster_drops = 10
	#Weight for a bow to drop from case
	#Range: 0 ~ 100
	bow_weight = 8
	#Animals drop chance
	#Range: 0 ~ 100
	animal_drops = 0
	#Minimum attack speed an axe can have.
	#Range: -4.0 ~ 4.0
	axe_a_speed = -3.0

#Traits Enabled
[traits]
	#Weakening Enabled?
	weakening_enabled = true
	#Webbed Enabled?
	webbed_enabled = true
	#More Fire Resistant Enabled?
	more_fire_resistant_enabled = true
	#Very Weakening Enabled?
	very_weakening_enabled = true
	#More Resistant Enabled?
	more_resistant_enabled = true
	#Floating Enabled?
	floating_enabled = true
	#Speedier Enabled?
	speedier_enabled = true
	#Bouncier Enabled?
	bouncier_enabled = true
	#Regenerating Enabled?
	regenerating_enabled = true
	#Soul Searching Enabled?
	soul_searching_enabled = true
	#Hastey Enabled?
	hastey_enabled = true
	#Super Lucky Enabled?
	super_lucky_enabled = true
	#Auto-smelt Enabled?
	auto-smelt_enabled = true
	#Blood Hunger Enabled?
	blood_hunger_enabled = true
	#Giant Slayer Enabled?
	giant_slayer_enabled = true
	#Very Withering Enabled?
	very_withering_enabled = true
	#Resistant Enabled?
	resistant_enabled = true
	#Bouncy Enabled?
	bouncy_enabled = true
	#Blood Thirst Enabled?
	blood_thirst_enabled = true
	#Hastier Enabled?
	hastier_enabled = true
	#Very Poisonous Enabled?
	very_poisonous_enabled = true
	#Cloud Walker Enabled?
	cloud_walker_enabled = true
	#Insightful Enabled?
	insightful_enabled = true
	#Glittering Enabled?
	glittering_enabled = true
	#Filling Enabled?
	filling_enabled = true
	#Strong Enabled?
	strong_enabled = true
	#Fire Resistant Enabled?
	fire_resistant_enabled = true
	#Poisonous Enabled?
	poisonous_enabled = true
	#Fortified Enabled?
	fortified_enabled = true
	#Double Webbed Enabled?
	double_webbed_enabled = true
	#Deep Breathing Enabled?
	deep_breathing_enabled = true
	#Withering Enabled?
	withering_enabled = true
	#Explosive Enabled?
	explosive_enabled = true
	#Phasing Enabled?
	phasing_enabled = true
	#Stronger Enabled?
	stronger_enabled = true
	#Lucky Enabled?
	lucky_enabled = true
	#Titan Slayer Enabled?
	titan_slayer_enabled = true
	#Speedy Enabled?
	speedy_enabled = true
	#Blinding Enabled?
	blinding_enabled = true
	#Infinity Edge Enabled?
	infinity_edge_enabled = true

