
#Client only settings
[client]
	#If true, disables all particle effects in the Reactor.
	disableReactorParticles = false
	#If true, no (advanced) tooltips will be added to blocks and items that can be used inside the Reactor or Turbine or as a fuel source.
	disableTurbineParticles = false

